AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  translatefunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 3008
      Timeout: 63
      Role: 'arn:aws:iam::017784105438:role/lambda-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          bucket: transcriptions-translations
